{
 "title": "Netology",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Load Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " 100 - (avg by(instance) (rate(node_cpu_seconds_total{instance=\"nodeexporter:9100\", mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "CPU load time"
    }
   ]
  },
  {
   "title": "Avalibale Memory GB",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes/1024^3",
     "legendFormat": "Avalibale Memory GB"
    }
   ]
  },
  {
   "title": "CPU Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "CPULA 1" },
    { "expr": "node_load5", "legendFormat": "CPULA 5" },
    { "expr": "node_load15", "legendFormat": "CPULA 15" }
   ]
  },
  {
   "title": "Disks Availible %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{fstype!~\"tmpfs|fuse.lxcfs|squashfs\"} / node_filesystem_size_bytes{fstype!~\"tmpfs|fuse.lxcfs|squashfs\"}*100",
     "legendFormat": "{{device}}   %"
    }
   ]
  }
 ]
}