FROM ubuntu

RUN apt update && \
    apt install -y wget && \
    apt install -y openjdk-11-jdk
WORKDIR /usr/local/jenkins
RUN wget https://get.jenkins.io/war-stable/2.289.1/jenkins.war
EXPOSE 8080
ENTRYPOINT ["java"]
CMD ["-jar","jenkins.war"]